[phases.setup]
nixPkgs = ["nodejs", "python3"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npx prisma generate"]

[start]
cmd = "python backend_runner.py"

[variables]
HOSTNAME = "0.0.0.0"
PORT = "8080"
