[phases.setup]
nixPkgs = ["nodejs", "python3"]

[phases.install]
cmds = [
  "echo '=== INSTALL PHASE START ==='",
  "echo 'Current directory:' && pwd",
  "echo 'Files in directory:' && ls -la",
  "echo 'Installing npm packages...'",
  "npm install --verbose",
  "echo '=== INSTALL PHASE COMPLETE ==='"
]

[phases.build]
cmds = [
  "echo '=== BUILD PHASE START ==='",
  "echo 'Generating Prisma client...'",
  "npx prisma generate",
  "echo 'Building Next.js app...'",
  "npm run build",
  "echo '=== BUILD PHASE COMPLETE ==='"
]

[start]
cmd = "npm start"
