[phases.setup]
nixPkgs = [
  "nodejs", 
  "python3", 
  "python3Packages.requests",
  "python3Packages.beautifulsoup4",
  "python3Packages.lxml",
  "python3Packages.openai",
  "python3Packages.python-dotenv",
  "python3Packages.httpx",
  "python3Packages.anthropic"
]

[phases.install]
cmds = [
  "npm install --production=false"
]

[phases.build]
cmds = [
  "npx prisma generate",
  "npm run build"
]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
