[build]
builder = "NIXPACKS"
watchPatterns = ["**/*"]

[deploy]
startCommand = "npm run railway:start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
port = 8080

[env]
NODE_ENV = "production"
RAILWAY_LOG_LEVEL = "debug"
PORT = "8080"
HOSTNAME = "0.0.0.0"
