[build]
builder = "NIXPACKS"
watchPatterns = ["**/*"]

[deploy]
startCommand = "npm run start:all"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
port = 8080

[env]
PYTHON_ENV = "production"
RAILWAY_LOG_LEVEL = "debug"
PORT = "8080"
HOSTNAME = "0.0.0.0"
